# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XJAsyncSocket' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'CocoaAsyncSocket'#长链接

end
